# Deploy n8n workflow files to Azure
name: Deploy to Azure Web App - paymentcalculator

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: n8n-workflow
          path: |
            workflows/
            README.md

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: n8n-workflow
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CB5F5E0AD6CD4F6394B69727119D902F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F72D2488EF8947D883B49DCDCE250919 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1A77A20A8B264544A0A0492F3CDCEBA5 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'paymentcalculator'
          slot-name: 'Production'
          package: .
